config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root "lists#index"
  resources :lists, only: [:show, :create, :destroy] do
    resources :bookmarks, only: :create
  end
  resources :bookmarks, only: :destroy
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list

  validates :comment, length: { minimum: 6 }
  validates :movie_id, :uniqueness => {:scope => :list_id}
end

# Un signet doit être lié à un film et une liste, et les associations [film, liste] doivent être uniques.

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks
  has_one_attached :photo

  validates :name, presence: true, uniqueness: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  validates :title, presence: true, uniqueness: true
  validates :overview, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  before_action :set_list, only: :create

  def create
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.list = @list
    if @bookmark.save
      redirect_to list_path(@list)
    else
      render 'lists/show', status: :unprocessable_entity
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy
    redirect_to list_path(@bookmark.list), status: :see_other
  end

  private

  def set_list
    @list = List.find(params[:list_id])
  end

  def bookmark_params
    params.require(:bookmark).permit(:movie_id, :list_id, :comment)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: [:show, :destroy]

  def index
    @lists = List.all.sort_by(&:name)
    @list = List.new
  end

  def show
    @bookmarks = @list.bookmarks
    @bookmark = Bookmark.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to list_path(@list)
    else
      render "lists/index", status: :unprocessable_entity
    end
  end

  def destroy
    @list.destroy
    redirect_to root_path, status: :see_other
  end

  private

  def set_list
    @list = List.find(params[:id])
  end

  def list_params
    params.require(:list).permit(:name, :photo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Watch List Manager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/_bookmark.html.erb
<div class="container">
  <div class="row">
      <% bookmarks.each do |bookmark| %>
        <% collection = bookmarks.select { |bookmark| bookmark.list_id == list.id } %>
        <% if collection.empty? %>
          <div class="col-12">
            <p>You haven't added any movie yet!</p>
            <% break %>
          </div>
        <% elsif bookmark.list_id == list.id %>
          <div class="col-3">
            <% movie = Movie.find(bookmark.movie_id) %>
              <div class="card" style="width: 18rem;">
                <img class="card-img-top" src="<%= movie.poster_url %>" alt="Poster for <%= movie.title%>">
                <div class="card-body">
                  <h5 class="card-title"><%= movie.title %></h5>
                  <p class="card-text"><%= movie.rating %></p>
                  <p class="card-text"><%= movie.overview %></p>
                  <h5>My comment</h5>
                  <p class="card-text"><%= bookmark.comment %></p>
                  <%= link_to "Delete this bookmark", bookmark_path(bookmark), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}, class: "btn btn-primary" %>
                </div>
              </div>
          </div>
        <% end %>
      <% end %>
    </div>
</div>

app/views/lists/_bookmark_form.html.erb
  <%= simple_form_for([@list, @bookmark]) do |f|%>
    <%= f.association :movie, collection: Movie.order('title ASC') %>
    <%= f.input :comment %>
    <%= f.submit "Add movie", class: "btn btn-dark" %>
  <% end %>

app/views/lists/_bookmark_list.html.erb
<div class="container">
  <div class="row gy-3">
    <% bookmarks.each do |bookmark| %>
      <div class="col-3">
        <% movie = Movie.find(bookmark.movie_id) %>
        <div class="card">
          <img class="card-img-top" src="<%= movie.poster_url %>" alt="Poster for <%= movie.title%>">
          <div class="card-body">
            <h5 class="card-title"><%= movie.title %></h5>
            <p class="card-text"><%= movie.rating %></p>
            <p class="card-text"><%= movie.overview %></p>
            <div class="comment-container">
              <h5>My comment</h5>
              <p class="card-text"><%= bookmark.comment %></p>
              <%= link_to "Remove from your list", bookmark_path(bookmark), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}, class: "btn" %>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/lists/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to "#", class: "navbar-brand" do %>
      <i class="fa-solid fa-clapperboard"></i>
    <% end %>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <%# if user_signed_in? %>
          <li class="nav-item dropdown">
            <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          </li>
        <%# else %>
          <!--li class="nav-item"-->
            <%#= link_to "Login", new_user_session_path, class: "nav-link" %>
          <!--/li-->
        <%# end %>
      </ul>
    </div>
  </div>
</div>

app/views/lists/index.html.erb
<%= render "navbar" %>

<div id="banner">
  <div id="banner-text">
    <h1>Watch List Manager</h1>
    <p>Never miss a good movie again</p>
  </div>
</div>

<div class="container">

    <h1>Your lists</h1>

<% if !List.all.empty? %>
  <div class="container">
    <div class="row">
      <% @lists.each do |list| %>
          <div class="col-3">
            <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= list.photo.attached? ? "#{cl_image_path(list.photo.key, height: 300, width: 400, crop: :fit)}" : "https://source.unsplash.com/random/400x300/?#{list.name}" %>">
              <%= link_to list.name, list_path(list) %>
            </div>
          </div>
      <% end %>
    </div>
  </div>
<% end %>



    <h3>Add a new list</h3>

<div class="container form-container">
    <%= simple_form_for(@list) do |f|%>
      <%= f.input :name %>
      <%= f.input :photo, as: :file %>
      <%= f.submit "Create a list", class: "btn btn-dark" %>
    <% end %>
</div>
</div>

app/views/lists/show.html.erb
<div class="container">
  <h1><%= @list.name %></h1>

  <% if @list.bookmarks.empty? %>
    <p>You haven't added any movie yet!</p>
  <% else %>
    <%= render "lists/bookmark_list", bookmarks: @list.bookmarks, list: @list %>
  <% end %>

  <div class="form-container">
    <h3>Add a movie to this watch list</h3>
    <%= render "lists/bookmark_form", list: @list, bookmark: @bookmark %>
  </div>

  <div class="links">
    <%= link_to "Back to my lists", root_path, class: "btn btn-secondary" %>
    <%= link_to "Delete this list", list_path(@list), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}, class: "btn destroy-btn" %>
  </div>
</div>